version: '3.7'

services:

  shiny:
    restart: always
    container_name: marine_shiny
    restart: always
    build:
      context: ../
      dockerfile: ./docker/shiny/Dockerfile
    image: marine/shiny
    env_file: ${ENV}
    volumes:
      - ..:/srv/shiny-server/
    ports:
      - 3838:3838

  postgres:
    # https://docs.docker.com/compose/compose-file/#container_name
    # just for demo purposes, scaling not possible when container name is used.
    container_name: marine_postgres
    restart: always
    build:
      context: ./postgres
      dockerfile: Dockerfile
    image: marine/postgres
    env_file: ${ENV}
    environment:
      - POSTGRES_DBNAME=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ..:/opt/shiny-data/
    ports:
      - 5432:5432

volumes:
  postgres-data: